language: node_js
node_js:
  - '9'
dist: trusty
sudo: required
branches:
  only:
    - master

before_script:
  - yarn install -g @angular/cli

script:
  - ng lint
  - yarn run build-site

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngu-translator
  on:
    branch: master
